// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4-OzPdfdpzdjp1PjM5Can4a0JhdSykto',
    appId: '1:791744060505:web:35c056a5a45308e7f2e548',
    messagingSenderId: '791744060505',
    projectId: 'mynotes-project-flutter-rico',
    authDomain: 'mynotes-project-flutter-rico.firebaseapp.com',
    storageBucket: 'mynotes-project-flutter-rico.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG0Ixt3KwAzJB6q2FQoCivyZApEZWviyo',
    appId: '1:791744060505:android:f467dbda79ffc117f2e548',
    messagingSenderId: '791744060505',
    projectId: 'mynotes-project-flutter-rico',
    storageBucket: 'mynotes-project-flutter-rico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMc7WUEY3FCcr5AhD0is_Gx6TpRhePoP4',
    appId: '1:791744060505:ios:8773f4d004d73d55f2e548',
    messagingSenderId: '791744060505',
    projectId: 'mynotes-project-flutter-rico',
    storageBucket: 'mynotes-project-flutter-rico.firebasestorage.app',
    iosBundleId: 'com.redbit.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMc7WUEY3FCcr5AhD0is_Gx6TpRhePoP4',
    appId: '1:791744060505:ios:8773f4d004d73d55f2e548',
    messagingSenderId: '791744060505',
    projectId: 'mynotes-project-flutter-rico',
    storageBucket: 'mynotes-project-flutter-rico.firebasestorage.app',
    iosBundleId: 'com.redbit.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4-OzPdfdpzdjp1PjM5Can4a0JhdSykto',
    appId: '1:791744060505:web:fa5e9c0d34cb1540f2e548',
    messagingSenderId: '791744060505',
    projectId: 'mynotes-project-flutter-rico',
    authDomain: 'mynotes-project-flutter-rico.firebaseapp.com',
    storageBucket: 'mynotes-project-flutter-rico.firebasestorage.app',
  );
}
